### ISSUE TITLE
Unittesting

### ISSUE THREAD

**Issue by RodneyAndresPerez** [CSE583-Electric-Cooking/e-cook#11]
only able to get unittests to work in `sparkboard/`. Can't do from `main dir`.

Using this command in terminal:
```
python -m unittest
```

Getting this error:
```
E
======================================================================
ERROR: sparkboard.tests.test_main (unittest.loader._FailedTest.sparkboard.tests.test_main)
----------------------------------------------------------------------
ImportError: Failed to import test module: sparkboard.tests.test_main
Traceback (most recent call last):
  File "/home/rodneyp/miniconda3/envs/ecook/lib/python3.12/unittest/loader.py", line 382, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodneyp/miniconda3/envs/ecook/lib/python3.12/unittest/loader.py", line 325, in _get_module_from_name
    __import__(name)
  File "/home/rodneyp/cse583/e-cook/sparkboard/tests/test_main.py", line 6, in <module>
    import plotting
ModuleNotFoundError: No module named 'plotting'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

However, works fine in `sparkboard`:
```
....../home/rodneyp/miniconda3/envs/ecook/lib/python3.12/site-packages/kaleido/scopes/base.py:188: DeprecationWarning:

setDaemon() is deprecated, set the daemon attribute instead

...........................
----------------------------------------------------------------------
Ran 33 tests in 9.978s

OK
```

Speculating on plotting import path in code.

**Comment by ericbehling** [comment]
rewrote code so that it import modules relative to where the location is. Adding __init__.py/relative stuff
